# Generated by Django 5.0.6 on 2024-05-20 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
